#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the encryption function below.
def encryption(s):
    row = int(math.ceil(len(s)**0.5))
    col = int(math.ceil(len(s)**0.5))
    out=''
    for i in range(col):
        for j in range(i,len(s),col):
            out+=s[j]
        out+=' '
    
    return out




if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = encryption(s)

    fptr.write(result + '\n')

    fptr.close()
