#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c, k):
    n =len(c)
    ene = 100
    i=0+k
    while True:
        print('i',i)
    
        if c[i] == 1:
            ene -= 3
        else:
            ene -= 1
        i=i+k
    
        print('en',ene)
        if(i%n)==0:
            if c[0]== 0 :
                return(ene-1)
            else:
                return(ene-3)
            break
        if i>n-1:
            i=i-n
            #print('i',i)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c, k)

    fptr.write(str(result) + '\n')

    fptr.close()
